version: '3.8'

services:
  nextdns-dashboard:
    build: .
    container_name: nextdns-analytics
    ports:
      - "5050:5050"
    restart: unless-stopped
    environment:
      - STREAMLIT_SERVER_PORT=5050
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
